const services=[
 ['Electricidad','Tableros, iluminación, enchufes y reparaciones eléctricas.','https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1200&q=82'],
 ['Gasfitería','Fugas, grifería, sanitarios, redes y reparaciones.','https://www.air1ac.com/images/imported/qm6x2jueqzi.jpg'],
 ['Climatización','Revisión, mantención y soporte de equipos HVAC.','https://gemcoservices.com/assets/home-grid-hvac.jpg'],
 ['Terminaciones','Pintura, carpintería, cerrajería y reparaciones menores.','https://irp.cdn-website.com/da08b59c/dms3rep/multi/1-40ffde9d.jpg'],
 ['Mantención preventiva','Inspecciones y acciones programadas para anticipar fallas.','https://cdn.shopify.com/s/files/1/0913/2104/1171/files/Preventative_Maintenance.jpg'],
 ['Mantención integral','Coordinamos múltiples especialidades con un único punto de contacto.','https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=82']
];
const sectors=['Edificios y oficinas','Restaurantes','Colegios','Retail','Centros logísticos','Activos inmobiliarios'];
export default function Page(){return <main>
<header><a className="brand" href="#"><span className="mark"><i></i><i></i><i></i></span><span><b>FACILITY</b><small>PARTNERS</small></span></a><nav><a href="#servicios">Servicios</a><a href="#sectores">Sectores</a><a href="#como">Cómo trabajamos</a><a className="navcta" href="mailto:contacto@facilitypartners.cl">Solicitar propuesta</a></nav></header>
<section className="hero"><video className="heroVideo" autoPlay muted loop playsInline poster="https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1800&q=82"><source src="/video/facility-partners-hero.mp4" type="video/mp4"/></video><div className="shade"></div><div className="heroContent"><div><span className="eyebrow">MANTENCIÓN INTEGRAL PARA EMPRESAS</span><h1>Tu mantención,<br/><em>resuelta con una llamada.</em></h1><p>Un fee mensual, con horas de mantención incluidas. Un solo partner para todas tus instalaciones.</p><a className="button" href="mailto:contacto@facilitypartners.cl">Solicitar propuesta →</a></div><div className="proof"><article><b>Presupuesto previsible</b><span>Planifica el costo anual.</span></article><article><b>Un solo partner</b><span>Centraliza tus necesidades.</span></article><article><b>Horas incluidas</b><span>Para resolver el día a día.</span></article></div></div></section>
<section className="statement"><span>UN PROBLEMA. UNA LLAMADA.</span><h2>Nosotros nos encargamos.</h2></section>
<section id="servicios" className="section"><span className="eyebrow dark">NUESTROS SERVICIOS</span><h2>Todo lo que tus instalaciones necesitan.</h2><div className="cards">{services.map(([t,d,img])=><article className="card" key={t}><div className="photo" style={{backgroundImage:`linear-gradient(180deg,transparent 45%,rgba(4,24,40,.75)),url(${img})`}}></div><div className="cardbody"><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
<section id="sectores" className="sectors"><div className="section"><span className="eyebrow">SECTORES</span><h2>Mantención para instalaciones que no pueden detenerse.</h2><div className="sectorgrid">{sectors.map(x=><div key={x}>{x}<span>→</span></div>)}</div></div></section>
<section id="como" className="section"><span className="eyebrow dark">CÓMO TRABAJAMOS</span><h2>Simple para ti. Coordinado por nosotros.</h2><div className="steps">{[['01','Evaluamos'],['02','Planificamos'],['03','Mantenemos'],['04','Resolvemos']].map(([n,t])=><article key={n}><b>{n}</b><h3>{t}</h3></article>)}</div></section>
<section className="model"><div><span className="eyebrow">UN MODELO MÁS SIMPLE</span><h2>Deja de improvisar cada reparación.</h2><p>Con Facility Partners tienes un fee mensual, una bolsa de horas de mantención y un único contacto para gestionar tus instalaciones.</p></div><a className="button light" href="mailto:contacto@facilitypartners.cl">Hablemos →</a></section>
<footer><div className="brand white"><span className="mark"><i></i><i></i><i></i></span><span><b>FACILITY</b><small>PARTNERS</small></span></div><span>Facility Partners · Chile</span></footer>
</main>}
